apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
        env: dev
    spec:
      containers:
      - name: echo-server
        image: gobdevel/echo-server:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

