apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echo-server
  template:
    metadata:
      labels:
        app: echo-server
        env: dev
    spec:
      containers:
      - name: echo-server
        image: gobdevel/echo-server:v1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            port: 8080
            path: /
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
        readinessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: 10
          periodSeconds: 3
        volumeMounts:
        - name: my-volume-1
          mountPath: "/var/volume-mount"
      volumes:
        - name: my-volume-1
          hostPath:
            path: /mnt/data
