kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: single-cluster
nodes:
- role: control-plane
  # port forward 80 on the host to 80 on this node
  extraPortMappings:
  - containerPort: 30000
    # Podman machine port starts from 30000
    hostPort: 30080
    # TCP is the default
    protocol: TCP
  # MongoDb Port
  - containerPort: 27017
    hostPort: 37017
    protocol: TCP
