# Docker Compose file for Ubuntu development machine
# Usage: Create an external volume named ubuntu-data
#
services:
  ubuntu-dev:
    image: 'ubuntu-dev:latest'
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ubuntu-dev
    hostname: ubuntu-dev
    restart: unless-stopped
    ports:
      - 2222:22
      - 4200:4200
      - 8000:8000
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
          memory: 4G 
        reservations:
          memory: 2G
    volumes:
      - ubuntu-data:/home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ubuntu-data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Library/A-Gobind/DockerShare/ubuntu_data'
