version: "3.9"
services:
  wiki:
    container_name: wiki
    image: requarks/wiki:latest
    hostname: tekyonix-wiki
    ports:
      - 3000:3000
    environment:
      DB_PASS_FILE: /run/secrets/db_password
    secrets:
      - db_password
    restart: unless-stopped

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: 256M
    networks:
      - tekyonix-network

    volumes:
      - /Users/gobindp/MyWork/wikijs-backup:/mnt/backup
      - ./configs/config.yml:/wiki/config.yml:ro

secrets:
  db_password:
    file: db_password.txt

networks:
  tekyonix-network:
    external: true

