version: "3.9"
services:
  wiki:
    container_name: wiki
    image: requarks/wiki:latest
    hostname: tekyonix-wiki
    ports:
      - 3000:3000
    environment:
      DB_TYPE: postgres
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: wikijs_admin
      DB_PASS_FILE: /run/secrets/db_password
      DB_NAME: wikijs
    secrets:
      - db_password
    restart: unless-stopped

    # deploy:
    #   resources:
    #     limits:
    #       cpus: '0.1'
    #       memory: 256M
    networks:
      - local-test-networks

secrets:
  db_password:
    file: db_password.txt

networks:
  local-test-networks:
    external: true

